Django/Appts/Appts/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.logreg_app.urls', namespace="logreg_app")),
    url(r'^appointments/', include('apps.appts_app.urls', namespace="appts_app"))
    
    ]


Django/Appts/apps/appts_app/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^create$', views.create, name="create"),
    url(r'^edit/(?P<appointment_id>\d+)$', views.edit, name="edit"),
    url(r'^update/(?P<appointment_id>\d+)$', views.update, name="update"),
    url(r'^delete/(?P<appointment_id>\d+)$', views.delete, name="delete"),
    url(r'^destroy/(?P<appointment_id>\d+)$', views.destroy, name="destroy")
]

Django/Appts/apps/logreg_app/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout")
    # url(r'^appointments$', )
]

Django/Appts/apps/appts_app/models.py
from __future__ import unicode_literals
from django.db import models


class Appointments(models.Model):
    start_time = models.TimeField()
    start_date = models.DateField()
    task = models.CharField(max_length=155)
    status = models.CharField(max_length=15, default="Pending")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    creator = models.ForeignKey("logreg_app.User", related_name="creator")
    # users_join = models.ManyToManyField()

Django/Appts/apps/logreg_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+.[a-zA-Z]*$')

class UserManager(models.Manager):
    def register(self, reg_data):
        full_name = reg_data['full_name']
        email = reg_data['email']
        birthday = reg_data['birthday']
        password = reg_data['password']
        confirm_password = reg_data['confirm_password']
        hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
        try:
            user = self.get(email=email)
        except:
            user = False
        if len(full_name) >2 and len(email) > 4 and EMAIL_REGEX.match(email) and birthday and len(password) >7 and password == confirm_password and not user:
        
            u = self.create(full_name=full_name, email=email, birthday=birthday, password=hashed)
            print u
            print reg_data
            return (True,u)
        return (False,"Try again using only letters in name and username and double check your password")

    def login(self, log_data):
        email = log_data['email']
        user = self.filter(email=email)
        password = log_data['password']
        if len(user) and bcrypt.hashpw(password.encode(), user[0].password.encode()) == user[0].password:
            return (True, user[0])
        return (False, 'Password or username are incorrect')



class User(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.CharField(max_length=150)
    birthday = models.DateField()
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

Django/Appts/apps/appts_app/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from .models import Appointments
from ..logreg_app.models import User
from django.contrib import messages
from datetime import datetime, date
from django.db.models import Q
now = datetime.now()


def index(request):
    if 'id' not in request.session:
        return redirect('/')
    user = User.objects.get(id=request.session["id"])
    context = {
        "today": Appointments.objects.filter(Q(start_date__lte=now, start_date__gte=now) & Q(creator__full_name=request.session["full_name"])),
        "future": Appointments.objects.filter(creator__full_name=request.session["full_name"]).exclude(start_date__lte=now)
    }
    return render(request, 'appts_app/index.html', context)


def edit(request, appointment_id):
    if 'id' not in request.session:
        return redirect(reverse('logreg_app:index'))
    context = {
        "appointment": Appointments.objects.get(id=appointment_id),
        "users": User.objects.all()
    }
    return render(request, 'appts_app/edit.html', context)


def create(request):
    if 'id' not in request.session:
        return redirect(reverse('logreg_app:index'))

    if request.POST["start_date"] and request.POST["start_time"] and request.POST["task"]:
        user = User.objects.get(id=request.session['id'])
        task = request.POST["task"]
        start_date = datetime.strptime(request.POST["start_date"], '%Y-%m-%d')
        start_time = datetime.strptime(request.POST["start_time"], '%H:%M')
        today = datetime(year=now.year, month=now.month, day=now.day)
        if start_date >= today:
            appointment = Appointments.objects.create(
                task=task, start_date=start_date, start_time=start_time, creator=user)
            return redirect(reverse('appts_app:index'))
        else:
            messages.add_message(request, messages.SUCCESS, 'Try again')
            return redirect(reverse('appts_app:index'))
    else:
        messages.add_message(request, messages.SUCCESS, 'Try again')
        return redirect(reverse('appts_app:indexindex'))


def update(request, appointment_id):
    if 'id' not in request.session:
        return redirect(reverse('logreg_app:index'))
    if request.POST["start_date"] and request.POST["start_time"] and request.POST["task"] and request.POST["status"]:
        a = Appointments.objects.get(id=appointment_id)
        a.task = request.POST["task"]
        a.status = request.POST["status"]
        a.start_date = datetime.strptime(
            request.POST["start_date"], '%Y-%m-%d')
        a.start_time = datetime.strptime(request.POST["start_time"], '%H:%M')
        today = datetime(year=now.year, month=now.month, day=now.day)
        if a.start_date >= today:
            a.save()
        else:
            print a.start_time
            messages.add_message(request, messages.SUCCESS, 'Try again')
            a = Appointments.objects.get(id=appointment_id)
            return redirect(reverse('appts_app:edit', kwargs={"appointment_id": a.id}))
    else:
        messages.add_message(request, messages.SUCCESS, 'Try again')
        a = Appointments.objects.get(id=appointment_id)
        return redirect(reverse('appts_app:edit', kwargs={"appointment_id": a.id}))
    return redirect(reverse('appts_app:index'))


def delete(request, appointment_id):
    if 'id' not in request.session:
        return redirect(reverse('logreg_app:index'))

    context = {
        "appointment": Appointments.objects.get(id=appointment_id),
        "users": User.objects.all()
    }
    return render(request, 'appts_app/delete.html', context)


def destroy(request, appointment_id):
    if 'id' not in request.session:
        return redirect(reverse('logreg_app:index'))
    appointment = Appointments.objects.get(id=appointment_id)
    appointment.delete()
    return redirect(reverse('appts_app:index'))

Django/Appts/apps/logreg_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from .models import User
from django.contrib import messages


def index(request):
    return render(request, 'logreg_app/index.html')


def login(request):
    # (True, user[0])
    # (False, 'Password or username are incorrect')
    user = User.objects.login(request.POST)
    if user[0]:
        request.session['full_name'] = user[1].full_name
        request.session['id'] = user[1].id
        return redirect('/appointments/')
        # return redirect('appts_app:index')
    messages.add_message(request, messages.SUCCESS, user[1])
    return redirect('/')


def register(request):
    user = User.objects.register(request.POST)
    print user[0], user[1]
    if user[0]:
        request.session['full_name'] = user[1].full_name
        request.session['id'] = user[1].id
        return redirect('/')
    messages.add_message(request, messages.SUCCESS)
    return redirect('/')


def logout(request):
    request.session.clear()
    return redirect('logreg_app:index')

Django/Appts/apps/appts_app/templates/appts_app/delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Delete</title>

</head>

<body>
    <div id="top">
        <a href="{% url 'logreg_app:logout' %}">Logout</a>
    </div>
    <h3>Are you sure you want to delete the following appointment?</h3>
    <p>Start Date: {{appointment.start_date}}</p>
    <p>Start Time: {{appointment.start_time}}</p>
    <p>Tasks: {{appointment.task}}</p>
    <form class="" action="{% url 'appts_app:index' %}" method="post">
        {% csrf_token %}
        <input type="submit" name="no" value="No">
    </form>
    <form action="{% url 'appts_app:destroy' appointment_id=appointment.id %}" method='POST'>
        {% csrf_token %}
        <input type="submit" name="yes" value="Yes! Delete this">
    </form>
</body>

</html>

Django/Appts/apps/appts_app/templates/appts_app/edit.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit</title>


</head>

<body>
    <div id="top">
        <a href="{% url 'appts_app:index' %}">Dashboard</a> |
        <a href="{% url 'logreg_app:logout' %}">Logout</a>
    </div>
    {% if messages %} {% for message in messages %}
    <h1>{{message}}</h1>
    {% endfor %} {% endif %}
    <form action="{% url 'appts_app:update' appointment_id=appointment.id %}" method="POST">
        {% csrf_token %}
        <label for="task">Tasks:</label>
        <input type="text" name="task" value="{{appointment.task}}">
        <p></p>
        <label for="status">Status:</label>
        <select name="status">
      <option value="current" selected="selected">{{appointment.status}}</option>
      <option value="Done">Done</option>
      <option value="Pending">Pending</option>
      <option value="Missed">Missed</option>
    </select>
        <p></p>
        <label for="start_date">Date:</label>
        <input type="date" name="start_date" value="{{appointment.start_date|date:'Y-m-d'}}">
        <p></p>
        <label for="start_time">Time:</label>
        <input type="time" name="start_time" value="{{appointment.start_time|time:'H:i'}}">
        <p></p>
        <input type="submit" value="Update">
    </form>

</body>

</html>

Django/Appts/apps/appts_app/templates/appts_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index</title>

</head>

<body>
    <div id="top">
        <a href="{% url 'logreg_app:logout' %}">Logout</a>
    </div>

    <h1>Hello, {{request.session.full_name}}</h1>

    <!-- {% if messages %} {% for message in messages %}
    <h1>{{message}}</h1>
    {% endfor %} {% endif %} -->
    <h2>Here are your appointments for today: {{request.session.datenow}}</h2>
    <table>
        <tr>
            <th>Tasks</th>
            <th>Time</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
        {% for appointment in today %}
        <tr>
            <td>{{appointment.task}}</td>
            <td>{{appointment.start_time}}</td>
            <td>{{appointment.status}}</td>
            {% if appointment.status != "Done" %}
            <td><a href="{% url 'appts_app:edit' appointment_id=appointment.id%}">Edit</a></td>
            <td><a href="{% url 'appts_app:delete' appointment_id=appointment.id%}">Delete</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>

    <h2>Your Other appointments</h2>
    <table>
        <tr>
            <th>Tasks</th>
            <th>Date</th>
            <th>Time</th>
        </tr>
        {% for appointment in future %}
        <tr>
            <td>{{appointment.task}}</td>
            <td>{{appointment.start_date}}</td>
            <td>{{appointment.start_time}}</td>
        </tr>
        {% endfor %}
    </table>

    <p></p>
    <h3>Add Appointment</h3>
    <div id="add_appointment">
        <form action="{% url 'appts_app:create' %}" method="POST">
            {% csrf_token %}
            <label for="start_date">Date:</label>
            <input type="date" name="start_date">
            <p></p>
            <label for="start_time">Time:</label>
            <input type="time" name="start_time">
            <p></p>
            <label for="task">Tasks:</label>
            <input type="text" name="task">
            <p></p>
            <input type="submit" value="Add">
        </form>
    </div>
    <h3>Other Users Appointments:</h3>
    <div>
        <table>
            <tr>
                <th>Tasks</th>
                <th>Time</th>
                <th>Status</th>
                <th>Action</th>
            </tr>

        </table>
    </div>
</body>

</html>

Django/Appts/apps/logreg_app/templates/logreg_app/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login and Reg | Home</title>
    <style>
        input {
            border-radius: 4px;
        }
        
        #register {
            background-color: #597eaa;
            color: white;
        }
        
        #login {
            background-color: #597eaa;
            color: white;
        }
    </style>
</head>

<body>

    <h1>Registration</h1>
    {% if messages and request.session.valid == "Register" %} {% for x in messages %}
    <p>{{ x.message }}</p>
    {% endfor %} {% endif %}


    <form action="{% url 'logreg_app:register' %}" method='POST'>
        {% csrf_token %}
        <label>Full Name:</label>
        <input type="text" name="full_name"><br>
        <label>Birthday:</label>
        <input type="date" name="birthday"><br>
        <label>Email:</label>
        <input type="text" name="email"><br>
        <label>Password:</label>
        <input type="password" name="password"><br>
        <label>Confrim Password:</label>
        <input type="password" name="confirm_password"><br>
        <input type="submit" value="Register" id="register">
    </form>
    <h1>Login</h1>
    {% if messages and request.session.valid == "Login" %} {% for x in messages %}
    <p>{{ x.message }}</p>
    {% endfor %} {% endif %}


    <form action="{% url 'logreg_app:login' %}" method='POST'>
        {% csrf_token %}
        <label>Email:</label>
        <input type="text" name="email"><br>
        <label>Password:</label>
        <input type="password" name="password"><br>
        <input type="submit" value="Login" id="login">
    </form>



</body>

</html>

Django/Appts/apps/logreg_app/templates/logreg_app/success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login and Reg | Success</title>
</head>

<body>
    <div id="wrapper">
        <h1>Hello, {{ user.first_name }}!</h1>
        <h4>Succesfully registered (or logged in)!</h4>
        {% if messages and request.session.valid == "Register" %} {% for x in messages %}
        <p>{{ x.message }}</p>
        {% endfor %} {% endif %}

        <a href="{% url 'logreg:logout' %}">Logout</a>
    </div>
</body>

</html>